# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-04 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.TextField()),
                ('sentimentValue', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
