# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-04 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sentimentValue',
        ),
    ]
