# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-04 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20170504_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sentiment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sentimentValue',
            field=models.FloatField(null=True),
        ),
    ]
